homebrew_repos: ['hashicorp/tap']
homebrew_cask_apps:
  - iterm2
  - visual-studio-code
homebrew_packages: ['ansible', 'ansible-lint', 'awscli', 'helm', 'kubernetes-cli', 'mas', 'openssl', 'hashicorp/tap/terraform', 'unzip', 'vim', 'wget']
python_dependencies:
  - requests
  - hvac
  - jira
  - python-gitlab