---
- name: Setup Mac Dev Environment
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - default.config.yml

  # pre_tasks:
  #   - name: Include playbook configuration.
  #     include_vars: "{{ item }}"
  #     with_fileglob:
  #       - "{{ playbook_dir }}/config.yml"
  #     tags: ['always']

  # roles:
  #   - role: 

  tasks:
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/python.yml
